### ISSUE TITLE
[BUG] Fix total amount (with installments) sent to InfinitePay API

### ISSUE THREAD

**Issue by panachi-cw** [cloudwalk/infinitepay-woocommerce-plugin#29]
Need to send the calculated amount with installments fee to InfinitePay API (the charged amount on CardHolder should reflect the total amount displayed on checkout [with interests])

Additional:
Show the additional amount (interests) on Order Totals

![Image](https://user-images.githubusercontent.com/104794820/183125298-5d52eac6-4b85-4f4e-825b-63ce203bc782.png)

**Comment by malkafly-cw** [comment]
@panachi-cw its done, how can i test?

**Comment by bru-carenzi** [comment]
@panachi-cw @malkafly-cw 

Hi guys! 

Could the rounding of the total amount of the interest-free charge be the fixed amount of the product? Because it can cause confusion to the user due to the change of values ​​between one installment and another. 

In the print below, you can see that amount interest-free change to 99,99 in 3x and in 6x the amount is 100,02. 



![Captura de Tela 2022-08-08 às 14 00 51](https://user-images.githubusercontent.com/93997860/183475551-04cfe127-ec73-485b-8735-99392f789a70.png)

**Comment by malkafly-cw** [comment]
Hey @bru-carenzi  fixed on front and backend

![image](https://user-images.githubusercontent.com/110417662/183491941-2af49677-d80e-4f1c-ad9f-31882aa0ae71.png)

**Comment by bru-carenzi** [comment]
Validated!


![Captura de Tela 2022-08-08 às 16 01 53](https://user-images.githubusercontent.com/93997860/183494108-3833a210-e10b-4f49-a8fb-b4f5b8b0449a.png)
